# -*- coding: utf-8 -*-
"""tamminimongodp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StTFnlJuLr177o5LSemfK2M8CNoX6e3j
"""

!pip install pymongo
!pip install streamlit

import streamlit as st
from pymongo import MongoClient
from datetime import datetime

# Set up MongoDB connection
client = MongoClient("mongodb+srv://tammeni25:MytamminiPass25!25@tammini.pcsh9ci.mongodb.net/?retryWrites=true&w=majority&appName=tammini")
db = client["tammini_db"]
users_col = db["users"]
responses_col = db["responses"]

st.set_page_config(page_title="منصة طَمّني", layout="centered", page_icon="🧠")

# ------------------ Auth Functions ------------------

def signup():
    st.subheader("🔐 تسجيل حساب جديد")
    username = st.text_input("اسم المستخدم")
    password = st.text_input("كلمة المرور", type="password")
    if st.button("تسجيل"):
        if users_col.find_one({"username": username}):
            st.error("اسم المستخدم مستخدم بالفعل.")
        else:
            users_col.insert_one({"username": username, "password": password})
            st.success("تم التسجيل! يمكنك الآن تسجيل الدخول.")

def login():
    st.subheader("🔑 تسجيل الدخول")
    username = st.text_input("اسم المستخدم")
    password = st.text_input("كلمة المرور", type="password")
    if st.button("دخول"):
        user = users_col.find_one({"username": username, "password": password})
        if user:
            st.session_state['user'] = username
            st.success("مرحباً بك، تم تسجيل الدخول.")
        else:
            st.error("بيانات الدخول غير صحيحة.")

# ------------------ Questionnaire Form ------------------

def questionnaire():
    st.subheader("📝 التقييم النفسي")
    gender = st.radio("ما هو جنسك؟", ["ذكر", "أنثى"])
    age = st.radio("ما هي فئتك العمرية؟", ["18-29", "30-39", "40-49", "50+"])

    q1 = st.text_area("س1: هل تعاني من التفكير المفرط أو القلق الزائد؟")
    q2 = st.text_area("س2: هل تجد صعوبة في السيطرة على هذه الأفكار؟")
    q3 = st.text_area("س3: ما الأعراض التي تعاني منها؟")
    q4 = st.text_area("س4: هل مررت بفترة مزاج مكتئب أو فقدان الشغف؟")
    q5 = st.text_area("س5: هل أثرت هذه الأعراض على حياتك اليومية؟")
    q6 = st.text_area("س6: هل هذه الأعراض ليست بسبب دواء أو حالة عضوية؟")

    if st.button("إرسال التقييم"):
        user = st.session_state.get('user')
        if user:
            responses_col.insert_one({
                "username": user,
                "gender": gender,
                "age": age,
                "q1": q1, "q2": q2, "q3": q3,
                "q4": q4, "q5": q5, "q6": q6,
                "timestamp": datetime.now()
            })
            st.success("✅ تم حفظ الإجابات.")
        else:
            st.error("⚠️ يرجى تسجيل الدخول أولاً.")

# ------------------ UI Navigation ------------------

st.markdown("""
    <div style='background-color:#001f4d;padding:30px;border-radius:10px;'>
        <h1 style='text-align:center;color:white;'>طَمّني</h1>
    </div>
    <div style='text-align:center;margin-top:40px;'>
        <h3 style='color:#666;'>Tameni platform for mental health diagnosis using AI</h3>
        <h2 style='color:#003366;'>منصة طَمّني لتقييم الصحة النفسية باستخدام الذكاء الصناعي</h2>
        <img src='https://cdn-icons-png.flaticon.com/512/4320/4320337.png' width='100' alt='brain'/>
    </div>
""", unsafe_allow_html=True)

if 'page' not in st.session_state:
    st.session_state.page = "landing"

if st.session_state.page == "landing":
    if st.button("Log in / Sign up"):
        st.session_state.page = "auth"
    st.stop()

if 'user' not in st.session_state:
    page = st.radio("اختر الصفحة", ["تسجيل الدخول", "تسجيل جديد"], horizontal=True)
    if page == "تسجيل الدخول":
        login()
    else:
        signup()
    st.stop()
else:
    questionnaire()

